import { createFileRoute, Link } from "@tanstack/react-router";
import { BriefcaseBusiness, Car, CircleDollarSign, ConciergeBell, HeartHandshake, Martini, Shirt, Soup, Utensils, Wifi } from "lucide-react";
import { Button } from "@/components/ui/button";
import { BookingStrip, PageHero, SectionTitle } from "@/components/site-shell";
import { Reveal } from "@/components/reveal";
import { pageHead, photos } from "@/lib/hotel";
export const Route=createFileRoute("/amenities")({head:()=>pageHead("Amenities | Hotel Beercastle Kufri","See confirmed amenities at Hotel Beercastle Kufri including free Wi-Fi, parking, restaurant, bar, room service and laundry service.","/amenities"),component:Amenities});
const amenities=[[Wifi,"Free Wi-Fi","Stay connected throughout your visit."],[Car,"Free Guest Parking","Convenient parking for hotel guests."],[ConciergeBell,"Room Service","Comfort and service brought to your room."],[Utensils,"On-Site Restaurant","Relaxed dining without leaving the property."],[Martini,"Bar","A comfortable place to unwind."],[Soup,"Paid Breakfast","Breakfast options available for guests."],[Shirt,"Laundry Service","Practical support for longer journeys."],[BriefcaseBusiness,"Business Center","Facilities for essential work needs."],[HeartHandshake,"Welcoming for All","Kids friendly and LGBTQ+ friendly."],[CircleDollarSign,"Golf Access","Golf access or facilities where applicable."]];
function Amenities(){return <><PageHero image={photos.receptionDining} eyebrow="Thoughtful essentials" title="Everything for an easy mountain stay." text="Practical comforts and warm service, whether you are here to explore, rest or work between journeys."/>
<section className="amenities-section"><Reveal><SectionTitle eyebrow="At the property" title="Comfort, considered." text="Confirmed facilities designed to keep your Kufri stay straightforward and comfortable."/></Reveal><div className="amenity-list">{amenities.map(([Icon,title,text],i)=><Reveal className="amenity-row" key={title as string}><span>{String(i+1).padStart(2,"0")}</span><Icon/><div><h3>{title as string}</h3><p>{text as string}</p></div></Reveal>)}</div></section>
<section className="amenity-feature"><img src={photos.loungeDining} alt="Shared lounge and dining area with timber ceiling"/><div><p className="eyebrow light">Space to gather</p><h2>Warm interiors.<br/>Unhurried moments.</h2><Button asChild variant="hero" size="xl"><Link to="/dining">Discover dining</Link></Button></div></section><BookingStrip/></>}