import { createFileRoute } from "@tanstack/react-router";
import { ArrowUpRight, MapPin, MessageCircle, Phone } from "lucide-react";
import { type FormEvent } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { PageHero } from "@/components/site-shell";
import { hotel, pageHead, photos } from "@/lib/hotel";
export const Route=createFileRoute("/contact")({head:()=>pageHead("Book Hotel Beercastle Kufri | Contact & Enquiry","Call, WhatsApp or send a booking enquiry to Hotel Beercastle Kufri on Apple Point Road near Mahasu Peak.","/contact"),component:Contact});
function Contact(){function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const msg=`Hello, I would like to enquire about booking a stay at Hotel Beercastle Kufri.\n\nName: ${form.get("name")}\nPhone: ${form.get("phone")}\nCheck-in: ${form.get("checkin")}\nCheck-out: ${form.get("checkout")}\nGuests: ${form.get("guests")}\nMessage: ${form.get("message")}`;window.open(`https://wa.me/918005794280?text=${encodeURIComponent(msg)}`,"_blank","noopener,noreferrer")};return <><PageHero image={photos.roomWindow} eyebrow="Plan your stay" title="Your Kufri escape starts here." text="Tell us your dates and we will help you plan a comfortable stay near Mahasu Peak."/>
<section className="contact-section"><div className="contact-details"><p className="eyebrow">Contact the hotel</p><h2>Speak with us directly.</h2><p>For room availability, seasonal prices and booking enquiries, call or send us a message.</p><a href={hotel.phoneHref} className="contact-line"><Phone/><span>Call Now<strong>{hotel.phone}</strong></span><ArrowUpRight/></a><a href={hotel.whatsapp} className="contact-line"><MessageCircle/><span>Book on WhatsApp<strong>Fast booking enquiry</strong></span><ArrowUpRight/></a><div className="address-line"><MapPin/><address>Apple Point Road,<br/>Mahasu Peak, Kufri,<br/>Himachal Pradesh 171209</address></div></div>
<form className="enquiry-form" onSubmit={submit}><div className="form-heading"><p className="eyebrow">Enquire now</p><h2>Check your dates.</h2></div><label>Name<Input name="name" required placeholder="Your full name"/></label><label>Phone<Input name="phone" required type="tel" placeholder="Your phone number"/></label><div className="form-pair"><label>Check-in<Input name="checkin" required type="date"/></label><label>Check-out<Input name="checkout" required type="date"/></label></div><label>Guests<Input name="guests" required type="number" min="1" placeholder="Number of guests"/></label><label>Message<Textarea name="message" rows={4} placeholder="Anything we should know?"/></label><Button type="submit" variant="gold" size="xl">Send enquiry on WhatsApp <ArrowUpRight/></Button><small>Your enquiry opens in WhatsApp. No information is stored on this website.</small></form></section></>}