import { createFileRoute } from "@tanstack/react-router";
import { ChevronLeft, ChevronRight, X } from "lucide-react";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { PageHero, SectionTitle } from "@/components/site-shell";
import { galleryPhotos, pageHead, photos } from "@/lib/hotel";
export const Route=createFileRoute("/gallery")({head:()=>pageHead("Gallery | Hotel Beercastle Kufri Photos","See real photos of Hotel Beercastle Kufri, its comfortable rooms, dining spaces and Himalayan hillside setting.","/gallery"),component:Gallery});
function Gallery(){const [selected,setSelected]=useState<number|null>(null);useEffect(()=>{if(selected===null)return;const key=(e:KeyboardEvent)=>{if(e.key==="Escape")setSelected(null);if(e.key==="ArrowRight")setSelected((selected+1)%galleryPhotos.length);if(e.key==="ArrowLeft")setSelected((selected-1+galleryPhotos.length)%galleryPhotos.length)};document.body.style.overflow="hidden";window.addEventListener("keydown",key);return()=>{document.body.style.overflow="";window.removeEventListener("keydown",key)}},[selected]);return <><PageHero image={photos.roomBlue} eyebrow="Hotel · Rooms · Kufri" title="A closer look at Beercastle." text="The real spaces, textures and mountain setting that shape a stay with us." align="center"/>
<section className="gallery-section"><SectionTitle eyebrow="The gallery" title="Inside the stay. Outside in the hills."/><div className="masonry">{galleryPhotos.map((photo,i)=><button type="button" className={`gallery-item gallery-item-${i+1}`} key={photo.src} onClick={()=>setSelected(i)} aria-label={`Open image: ${photo.alt}`}><img src={photo.src} alt={photo.alt}/><span>View</span></button>)}</div></section>
{selected!==null&&<div className="lightbox" role="dialog" aria-modal="true" aria-label="Hotel photo viewer"><Button variant="nav" size="icon" className="lightbox-close" onClick={()=>setSelected(null)} aria-label="Close gallery"><X/></Button><Button variant="nav" size="icon" className="lightbox-prev" onClick={()=>setSelected((selected-1+galleryPhotos.length)%galleryPhotos.length)} aria-label="Previous image"><ChevronLeft/></Button><img src={galleryPhotos[selected]?.src} alt={galleryPhotos[selected]?.alt}/><Button variant="nav" size="icon" className="lightbox-next" onClick={()=>setSelected((selected+1)%galleryPhotos.length)} aria-label="Next image"><ChevronRight/></Button><p>{String(selected+1).padStart(2,"0")} / {galleryPhotos.length} · {galleryPhotos[selected]?.alt}</p></div>}</>}